services:
  - type: web
    name: myapp
    runtime: python
    plan: free
    buildCommand: "poetry install --no-root"
    startCommand: "poetry run gunicorn app:app"
    envVars:
      - key: PYTHON_VERSION
        value: "3.10.9"
      - key: POETRY_VERSION
        value: "1.3.2"
      - key: ICALPROC_BASE_URL
        # Will allow setting custom value during deploy.
        # Example: https://my-ical-processor.onrender.com
        sync: false
